### ISSUE TITLE
Questino about how to get the performance

### ISSUE THREAD

**Issue by BackMountainDevil** [LiangZhang1996/AttentionLight#5]
[paper](https://arxiv.org/abs/2201.00006v3): "Table 1. Overall performance. For average travel time, the smaller the better."

In the code, to get the att(average travel time), run the summary.py and get data from file and then calculate the att. 

But I find we can get it from CityFlow.eng: `self.eng.get_average_travel_time()`. Why not use that as att result? Is there a diff?

**Comment by LiangZhang1996** [comment]
These two calculation methods indeed yield different results. As for how significant this difference is, and why one method is not used over the other, we have not yet systematically studied.

**Comment by BackMountainDevil** [comment]
Thanks for your kindly explaination. It is happy to know they are not the same.I will try to ask CoLight
