### ISSUE TITLE
func get_lane_length calculations is wrong in some cases

### ISSUE THREAD

**Issue by BackMountainDevil** [LiangZhang1996/AttentionLight#6]
https://github.com/LiangZhang1996/AttentionLight/blob/f90204ba1799314f29b7dd7d8cb3cc4fb6d1b267/utils/cityflow_env.py#L615-L625

that will got error in this case:

```
"id": "road_20_1_1",
"points": [
    {
    "x": 5700,
    "y": 0
    },
    {
    "x": 5400,
    "y": 300
    }
],
```
road_length will be 0 if use that calculation way(5700+0 -5400-300 ==0), this 0 will set min_length to 0, and will cause div0 exception before return at L624

a possible solution:

```python
road_length = sqrt((points[0]['x']-points[1]['x'])**2 + (points[0]['y']-points[1]['y'])**2) #  should be int ? 
assert road_length>0, 'Error road length(' + str(road_length) +') is too short. road info: ' + str(road)
```

**Comment by LiangZhang1996** [comment]
Thank you very much for raising this question. In the examples I frequently use, roads are typically depicted as straight and level, without considering the scenario you mentioned. Additionally, this function is not utilized in this project.

**Comment by BackMountainDevil** [comment]
got it. hope this help those who use non-grid data
